import type { House } from "./types";

export const houses: House[] = [
  {
    id: "1",
    address: "123 Maple Street, Springfield",
    price: 300000,
    coordinates: [40.7128, -74.0060], // New York City (for demo)
    size: 150,
    rooms: 4,
    year: 1995,
    wallMaterial: "Brick",
    buildingSeries: "Colonial",
    floors: 2,
    hasElevator: false,
    floorType: "Hardwood",
    foundationType: "Concrete Slab",
    hasGarbageChute: false,
    hotWaterSupply: "Centralized",
    floorPlanUrl: "https://picsum.photos/seed/fp1/800/600",
    floorPlanHint: "floor plan",
  },
  {
    id: "2",
    address: "456 Oak Avenue, Metropolis",
    price: 450000,
    coordinates: [40.730, -73.990], // Near NYC
    size: 200,
    rooms: 5,
    year: 2010,
    wallMaterial: "Concrete Panel",
    buildingSeries: "Modern High-Rise",
    floors: 25,
    hasElevator: true,
    floorType: "Reinforced Concrete",
    foundationType: "Pile",
    hasGarbageChute: true,
    hotWaterSupply: "Autonomous Boiler",
    floorPlanUrl: "https://picsum.photos/seed/fp2/800/600",
    floorPlanHint: "blueprint drawing",
  },
  {
    id: "3",
    address: "789 Pine Lane, Gotham",
    price: 220000,
    coordinates: [40.705, -74.010], // Near NYC
    size: 120,
    rooms: 3,
    year: 1982,
    wallMaterial: "Wood Frame",
    buildingSeries: "Ranch",
    floors: 1,
    hasElevator: false,
    floorType: "Wood",
    foundationType: "Crawl Space",
    hasGarbageChute: false,
    hotWaterSupply: "Gas Water Heater",
    floorPlanUrl: "https://picsum.photos/seed/fp3/800/600",
    floorPlanHint: "architectural plan",
  },
  {
    id: "4",
    address: "101 Elm Street, Star City",
    price: 600000,
    coordinates: [40.725, -74.005], // Near NYC
    size: 250,
    rooms: 6,
    year: 2021,
    wallMaterial: "Glass Curtain",
    buildingSeries: "Luxury Condo",
    floors: 40,
    hasElevator: true,
    floorType: "Composite",
    foundationType: "Mat Foundation",
    hasGarbageChute: true,
    hotWaterSupply: "Centralized",
    floorPlanUrl: "https://picsum.photos/seed/fp4/800/600",
    floorPlanHint: "apartment layout",
  },
  {
    id: "5",
    address: "212 Birch Road, Central City",
    price: 180000,
    coordinates: [40.718, -73.998], // Near NYC
    size: 90,
    rooms: 2,
    year: 1975,
    wallMaterial: "Brick",
    buildingSeries: "Pre-War Walk-up",
    floors: 5,
    hasElevator: false,
    floorType: "Wood",
    foundationType: "Basement",
    hasGarbageChute: false,
    hotWaterSupply: "Tankless Heater",
    floorPlanUrl: "https://picsum.photos/seed/fp5/800/600",
    floorPlanHint: "room sketch",
  },
];
